- name: Installations diverses
  hosts: hosts
  become: yes
  vars_files: ../vars/main.yml
  tasks:
    - name: Installation des packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"