---
- name: Créer des utilisateurs, configurer leurs clés SSH et définir les limites de ressources
  hosts: hosts
  gather_facts: false
  become: yes
  vars_files: ../vars/main.yml
  tasks:
    - name: Créer un groupe personnalisé par user
      group:
        name: "{{ item.username }}"
      loop: "{{ users_to_create }}"

    - name: Créer les utilisateurs
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        state: present
        shell: /bin/bash
        group: "{{ item.username }}"
        home: "/home/{{ item.username }}"
      loop: "{{ users_to_create }}"
      register: __user

    - name: Debug user
      debug:
        var: __user

    - name: Ajouter les clés SSH autorisées pour les utilisateurs
      lineinfile:
        path: "/home/{{ item.username }}/.ssh/authorized_keys"
        line: "{{ item.ssh_key }}"
        create: yes
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: "0600"
      loop: "{{ users_to_create }}"

    - name: Créer le groupe wheel
      group:
        name: wheel
        state: present

    - name: Gérer l'appartenance au groupe "wheel"
      user:
        name: "{{ item.username }}"
        groups: "wheel"
      loop: "{{ users_to_create }}"
      when: item.wheel == "yes"

    - name: Ajouter l'utilisateur par défaut aux groupes "wheel" et "sudo"
      user:
        name: "{{ default_user }}"
        groups: "wheel,sudo"

    - name: Forcer le changement de mot de passe à la première connexion
      command: chage -d 0 {{ item.username }}
      loop: "{{ users_to_create }}"


